spring.application.name=CodeAlpha-Java-Gradle-App

server.port=8080

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=CodeAlpha Java Gradle Application
info.app.description=Java Application using Gradle - CodeAlpha DevOps Internship Task 3
info.app.version=1.0.0
info.app.java=17
info.app.build-tool=Gradle